# ==========================================
# APLICACION
# ==========================================
spring.application.name=baezpos

# ==========================================
# BASE DE DATOS (MySQL)
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:baezpos_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:38216639}

# ==========================================
# JPA / HIBERNATE (MySQL)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Buenas practicas de rendimiento
spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false

# ==========================================
# SERVICIO DE CORREO (SMTP - Puerto 587)
# ==========================================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:${MAIL_USERNAME:alexanderbaez146@gmail.com}}
spring.mail.password=${SPRING_MAIL_PASSWORD:${MAIL_PASSWORD:nraficpwupqpmbts}}

# Configuracion STARTTLS estandar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

# Timeouts de red para evitar bloqueos
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# ==========================================
# CREDENCIALES MAESTRAS (SuperAdmin SaaS)
# ==========================================
app.superadmin.email=${SUPERADMIN_EMAIL:alexanderbaez146@gmail.com}
app.superadmin.password=${SUPERADMIN_PASSWORD:Alexander.38216639}

# ==========================================
# LOGS & THYMELEAF
# ==========================================
logging.level.org.springframework.security=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false